# Generated by Django 5.1.7 on 2025-03-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalStats',
            fields=[
                ('singleton_instance_id', models.PositiveIntegerField(default=1, editable=False, primary_key=True, serialize=False, unique=True)),
                ('total_questions_served', models.PositiveIntegerField(default=0, help_text='Contador total de perguntas oficiais servidas pela API.')),
            ],
            options={
                'verbose_name': 'Estatística Global',
                'verbose_name_plural': 'Estatísticas Globais',
            },
        ),
    ]
